"""FastAPI server for streaming stock query agent."""

import logging
import os
import json
from typing import AsyncGenerator
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from dotenv import load_dotenv
from litellm import completion

from session_manager import SessionManager
from agent import (
    STOCK_TOOLS,
    get_system_prompt,
    execute_tool_call,
)


load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s,p%(process)s,{%(filename)s:%(lineno)d},%(levelname)s,%(message)s",
)
logger = logging.getLogger(__name__)


HOST = os.getenv("HOST", "127.0.0.1")
PORT = int(os.getenv("PORT", "5003"))
MAX_HISTORY_SIZE = int(os.getenv("MAX_HISTORY_SIZE", "100"))
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not GROQ_API_KEY:
    raise ValueError("GROQ_API_KEY environment variable is required")


session_manager = SessionManager(max_history_size=MAX_HISTORY_SIZE)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Lifespan context manager for startup and shutdown."""
    logger.info(f"Starting Stock Query Agent API on {HOST}:{PORT}")
    logger.info(f"Max conversation history size: {MAX_HISTORY_SIZE}")
    yield
    logger.info("Shutting down Stock Query Agent API")


app = FastAPI(
    title="Stock Query Agent API",
    description="Streaming conversational agent for stock market queries",
    version="1.0.0",
    lifespan=lifespan
)


class InvocationRequest(BaseModel):
    """Request model for agent invocation."""

    session_id: str = Field(
        ...,
        description="Unique session ID for conversation tracking"
    )
    message: str = Field(
        ...,
        description="User message/query"
    )


class PingResponse(BaseModel):
    """Response model for health check."""

    status: str = Field(default="ok")


def _convert_tools_for_litellm():
    """Convert tool definitions to LiteLLM format."""
    return [
        {
            "type": "function",
            "function": {
                "name": tool["name"],
                "description": tool["description"],
                "parameters": tool["parameters"]
            }
        }
        for tool in STOCK_TOOLS
    ]


async def _stream_agent_response(
    session_id: str,
    user_message: str
) -> AsyncGenerator[str, None]:
    """Stream agent response with tool calling support.

    Yields text chunks as they're generated by the LLM.
    """
    try:
        session_manager.add_message(session_id, "user", user_message)

        conversation_history = session_manager.get_history(session_id)

        messages = [
            {"role": "system", "content": get_system_prompt()}
        ] + conversation_history

        tools = _convert_tools_for_litellm()

        max_iterations = 5
        iteration = 0

        while iteration < max_iterations:
            iteration += 1

            try:
                response = completion(
                    model="groq/qwen/qwen3-32b",
                    messages=messages,
                    tools=tools,
                    stream=True,
                    api_key=GROQ_API_KEY
                )
            except Exception as e:
                logger.error(f"Error calling LLM: {e}")
                yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
                break

            accumulated_content = ""
            tool_calls = []
            current_tool_call = None

            for chunk in response:
                delta = chunk.choices[0].delta if chunk.choices else None

                if not delta:
                    continue

                if hasattr(delta, 'content') and delta.content:
                    accumulated_content += delta.content
                    yield f"data: {json.dumps({'type': 'text', 'content': delta.content})}\n\n"

                if hasattr(delta, 'tool_calls') and delta.tool_calls:
                    for tc in delta.tool_calls:
                        if tc.index is not None:
                            if current_tool_call is None or tc.index != current_tool_call.get('index'):
                                if current_tool_call:
                                    tool_calls.append(current_tool_call)
                                current_tool_call = {
                                    'index': tc.index,
                                    'id': tc.id if hasattr(tc, 'id') and tc.id else f"call_{tc.index}",
                                    'function': {
                                        'name': tc.function.name if hasattr(tc.function, 'name') and tc.function.name else '',
                                        'arguments': tc.function.arguments if hasattr(tc.function, 'arguments') and tc.function.arguments else ''
                                    }
                                }
                            else:
                                if hasattr(tc.function, 'name') and tc.function.name:
                                    current_tool_call['function']['name'] = tc.function.name
                                if hasattr(tc.function, 'arguments') and tc.function.arguments:
                                    current_tool_call['function']['arguments'] += tc.function.arguments

            if current_tool_call:
                tool_calls.append(current_tool_call)

            if tool_calls:
                yield f"data: {json.dumps({'type': 'tool_calls_start'})}\n\n"

                messages.append({
                    "role": "assistant",
                    "content": accumulated_content if accumulated_content else None,
                    "tool_calls": [
                        {
                            "id": tc['id'],
                            "type": "function",
                            "function": {
                                "name": tc['function']['name'],
                                "arguments": tc['function']['arguments']
                            }
                        }
                        for tc in tool_calls
                    ]
                })

                for tool_call in tool_calls:
                    tool_name = tool_call['function']['name']
                    tool_args_str = tool_call['function']['arguments']

                    try:
                        tool_args = json.loads(tool_args_str) if tool_args_str else {}
                    except json.JSONDecodeError:
                        tool_args = {}

                    yield f"data: {json.dumps({'type': 'tool_call', 'name': tool_name, 'args': tool_args})}\n\n"

                    tool_result = execute_tool_call(tool_name, tool_args)

                    messages.append({
                        "role": "tool",
                        "tool_call_id": tool_call['id'],
                        "name": tool_name,
                        "content": tool_result
                    })

                yield f"data: {json.dumps({'type': 'tool_calls_end'})}\n\n"

            else:
                # Save only the final assistant response to avoid tool call structure issues
                if accumulated_content:
                    session_manager.add_message(session_id, "assistant", accumulated_content)
                yield f"data: {json.dumps({'type': 'done'})}\n\n"
                break

        if iteration >= max_iterations:
            error_msg = "Maximum iterations reached"
            yield f"data: {json.dumps({'type': 'error', 'message': error_msg})}\n\n"

    except Exception as e:
        logger.exception(f"Error in agent response stream: {e}")
        yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"


@app.get("/ping", response_model=PingResponse)
async def ping():
    """Health check endpoint."""
    return PingResponse(status="ok")


@app.post("/invocation")
async def invocation(request: InvocationRequest):
    """Invoke the agent with a user message.

    Returns a streaming response with Server-Sent Events (SSE).
    """
    logger.info(
        f"Invocation request - session_id: {request.session_id}, "
        f"message: {request.message[:50]}..."
    )

    return StreamingResponse(
        _stream_agent_response(request.session_id, request.message),
        media_type="text/event-stream"
    )


@app.get("/session/{session_id}/info")
async def get_session_info(session_id: str):
    """Get information about a session."""
    info = session_manager.get_session_info(session_id)

    if not info:
        raise HTTPException(status_code=404, detail="Session not found")

    return info


@app.delete("/session/{session_id}")
async def delete_session(session_id: str):
    """Delete a session and its history."""
    deleted = session_manager.delete_session(session_id)

    if not deleted:
        raise HTTPException(status_code=404, detail="Session not found")

    return {"status": "deleted", "session_id": session_id}


@app.get("/sessions/count")
async def get_sessions_count():
    """Get total number of active sessions."""
    return {"count": session_manager.get_session_count()}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        app,
        host=HOST,
        port=PORT,
        log_level="info"
    )
